### ISSUE TITLE
bug反馈

### ISSUE THREAD

**Issue by KasumiYuku** [xiaoye12123/Shiranai-Plugin#4]
连连看只能电脑端用，因为手机端点击一个按钮后点击另外一个按钮时，第一个点击的按钮会被清空。

消灭星星会重复发送两遍:
![image](https://github.com/XasYer/Shiranai-Plugin/assets/107661829/176e6bbd-270e-4724-9cc2-85310be279d0)

**Comment by lava081** [comment]
连连看未见异常
消灭星星根据游玩体验，应为消灭半屏(上5行)的星星，所以需要两个keyboard
